apiVersion: v1
kind: Service
metadata:
    name: {{ include "horizon-webapp.fullname" . }}
    labels:
        app: {{ include "horizon-webapp.name" . }}
        chart: {{ include "horizon-webapp.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app: {{ include "horizon-webapp.name" . }}
        release: {{ .Release.Name }}
