export const GET_INTEREST = 'GET_INTEREST';
export const GET_INTEREST_SUCCESS = 'GET_INTEREST_SUCCESS';
export const GET_INTEREST_FAILED = 'GET_INTEREST_FAILED';
export const SET_INTEREST = 'SET_INTEREST';
export const SET_INTEREST_SUCCESS = 'SET_INTEREST_SUCCESS';
export const SET_INTEREST_FAILED = 'SET_INTEREST_FAILED';
