export const GET_SECURITY_STREAM = 'GET_SECURITY_STREAM';
export const GET_SECURITY_STREAM_SUCCESS = 'GET_SECURITY_STREAM_SUCCESS';
export const GET_SECURITY_STREAM_FAILED = 'GET_SECURITY_STREAM_FAILED';
