export const GET_SOC_ANNOUNCEMENT = 'GET_SOC_ANNOUNCEMENT';
export const GET_SOC_ANNOUNCEMENT_SUCCESS = 'GET_SOC_ANNOUNCEMENT_SUCCESS';
export const GET_SOC_ANNOUNCEMENT_FAILED = 'GET_SOC_ANNOUNCEMENT_FAILED';
