bffUrl: "https://api.us.apiconnect.ibmcloud.com/mssace-dev/sb/"
corsAllowOrigin: https://dev-center.sec.ibm.com
ibmIdIssuer: https://prepiam.ice.ibmcloud.com/oidc/endpoint/default
piwik:
  siteId: 14
ingress:
  enabled: true
  annotations: {
    ingress.bluemix.net/redirect-to-https: "True"
  }
  path: /
  hosts:
    - dev-center.sec.ibm.com
  tls:
    - secretName: wc.sec.ibm.com
      hosts:
        - dev-center.sec.ibm.com
